apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: mongo_uri
  namespace: solar-system
spec:
  encryptedData:
    MONGO_URI: AgAk6EZSMgkCwpddcUd3fERqDrYuZAPrY6TA2F4sq/FtWA+8pxc+TFixdlDvNdR6PGrWtpG563Ym9Qr/xMTUnqlxeRy4VUojO/RVzIjA/LRABo69Q8LZjIiyRF0NYbVshPhdMlQI1r2YOHTjdrQwop3/n5Fr01rcoeKKThkRtATLy4opAqkx0rMeA/nJnOZm+btDRugFhIT0zcCfesWRMAdY0nehbfu7+5GOQUpsfXW83kWsWn2jeISROpDniTfLMsv+GlsjL7X7oFaOeKuJCEDpFTK/z7M/nJDwx8lmeIIFNxbSUZ3KjowGWEQI8juBQ1CWY4OumAnpRxUK3QLW+iggMwJi7wf4NkoTb+7o78exlSv9ptlJIzdtdwTKvFw5PY+V77iwj6zyqfWtYUSBFtrW3OPGQGZ7e0n1X/56NMuRhU4Ri0VPizw19LFSjcAuCIk+UPCLAqpCTeeI98gNdcbeEnuRE160UbvX+8lOMg/eJUfVDSlGtzCxQZ47jSqv97LYRBmZnUUmdZ84+3x8P+X9QGN7wUUmSIa4KcSEjYS83eWxP3oM0OIFVxX2ejohFxDEPaBL1cZE/GbYMp1l+856yczQrRNOfi8blPxGvjBhCWKectwaBMSkjBG8TfeUrG37nq6k8mMlVrUzFZW8DB0+6ickpYaGm+yyPNDTeHyRoucqODe6vZuZTeMrSdh5x2eJwtL3ZOlvSNhIRpxuFaw34d9KsOL+uaMKBFhA7XvSAqTZaFBXxsKuYM7F/iPVO91Gx6k/l4I5vwV8NuPaHA1+TgbP/HxWTYAMkVAMX8M=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: mongo_uri
      namespace: solar-system